name: Codegen Publisher

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - packages/codegen/pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # - name: Validate
      #   uses: peiffer-innovations/actions-flutter-validate@v2
      #   with:
      #     path: packages/codegen

      - name: Publish
        uses: peiffer-innovations/actions-pub-publish@v1.0.2
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}
          path: packages/codegen
